### ISSUE TITLE
Add more properties for CommandAttribute

### ISSUE THREAD

**Issue by redplcs** [game-creators-area/Advisor#3]
**Name of the requested feature/enhancement:**
Expanding properties?

**Description:**
Instead of having this compact code
```csharp
[Command("do-stuff", SandboxRealm.Shared, Description = "This command doing some stuff!", Target = TargetPermission.All)]
public void DoStuff()
{
}
```

we have
```csharp
[Command("do-stuff", SandboxRealm.Shared)]
[Description("This command doing some stuff!")]
[Target(TargetPermission.All)]
public void DoStuff()
{
}
```

**Additional context**
Don't have

**Comment by Erlite** [comment]
I guess that's something we can do yeah, I mostly went for multiple attributes to avoid having a long attribute declaration, but it can be made a little more compact.

Feel free to grab it if you'd like, else I'll do it once I'm done with another part of the command stuff.
